version: "3"

services: 
    db:
        image: mysql
        security_opt:
            - seccomp:unconfined
        environment: 
            - MYSQL_ROOT_PASSWORD=sn726300 # 用户密码
            - MYSQL_DATABASE=rice # 数据库名称
        ports:
            - "3306:3306" # 与配置文件保持一致
        networks:
            - net
        restart: always
        command: --character-set-server=utf8mb4
        # volumes: 
   
    web:
        build: ./riceprediction # 使用该目录下的Dockerfile
        volumes: 
            - "./riceprediction:/gBreeder"
        depends_on: # 依赖关系
            - db
        environment:
            - DEBUG=False
            - TZ=Asia/Shanghai
        restart: always
        ports:
            - "8000:5000" # 与配置文件保持一致
        networks:
            - net
        tty: true
        stdin_open: true
     
networks:
    net:
